function [BW,maskedImage] = lung_region(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 08-Mar-2021
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% 阈值化图像 - 手动阈值
BW = X > 5.019600e-01;

% 反转掩膜
BW = imcomplement(BW);

% 清理边框
BW = imclearborder(BW);

BW = imfill(BW, 'holes');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

